version: 2
jobs:
  build:
    steps:
       - run: sudo apt-get install -y libsqlite3-dev
       - run: cp .env.testing .env
       - run: composer install -n --ignore-platform-reqs
       - run: npm install
       - run: npm run production
       - run: vendor/bin/phpun
       - run:
          name: Start Chrome Driver
          command: ./vendor/laravel/dusk/bin/chromedriver-linux
          background: tr
       - run:
          name: Run Laravel Server
          command: php artisan serve
          background: tr
       - run:
          name: Run Laravel Dusk Tests
          command: php artisan dusk

  deploy:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${KEY_FINGERPRINT}"  
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/app/ && git pull origin master '

 
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master