version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.0-node-browsers
      - image: circleci/mariadb:10.4
    environment:
      - DB_CONNECTION: circle_testing
    working_directory: ~/p
    steps:
     - run: ls
     - run: sudo apt-get install -y libsqlite3-dev
     - run: composer install -n --ignore-platform-reqs
     - run: npm install
     - run: npm run production
     - run: cd app && vendor/bin/phpu 
     - run:
         name: Start Chrome Driver
         command: cd app && ./vendor/laravel/dusk/bin/chromedriver-linux
         background: true

     - run:
         name: Run Laravel Server
         command: cd app && php artisan serve
         background: true

     - run:
         name: Run Laravel Dusk Tests
         command: cd app && php artisan dusk

  deploy:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${KEY_FINGERPRINT}"  
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/app/ && git pull origin master '

 
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master