version: 2 # 設定ファイルのバージョン
jobs: # 実行させたいジョブの定義
  build: # ジョブ名を定義する
    docker: # ジョブを実行するマシンを定義
      # CircleCIのイメージを使用
      - image: circleci/php:7.2-node-browsers
      - image: circleci/mysql:5.7
    environment:
      - DB_CONNECTION: circle_testing
    working_directory: ~/p
    steps: # マシンに対しての命令手順
      - checkout # コードをレポジトリからチェックアウト
      - run: # コマンドを実行
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          working_directory: src
          command: composer update
      - run:
          name: Install PHP libraries
          working_directory: src
          command: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "src/composer.json" }}
      - run:
          name: Run PHPUnit
          working_directory: src
          command: vendor/bin/phpunit
 
 
  # deploy:
  #   machine:
  #     image: circleci/classic:edge
  #   steps:
  #     - add_ssh_keys:
  #         fingerprints:
  #           - "84:○:○:○:○:○:○:○:○:○:○:○:○:○:○:bf"
  #     - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/app/ && git pull origin master'
 
# workflows:
#   version: 2
#   build_and_deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master