version: 2
jobs:
  build:
    docker:
      - image: dyoshikawa/laravel:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install Composer Packages
          command: |
            cd app && composer install
      - run: cd app && cp .env.testing .env
      - run: docker-compose build
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for MySQL
          command: |
             cd app && dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Migrate DB
          command: |
             cd app && php artisan migrate
      - run:
          name: Migrate DB
          command: |
             cd app && php artisan dusk

    # build:
    # docker:
    #   - image: circleci/php:7.3.0-node-browsers
    #   - image: circleci/mariadb:10.4
    # environment:
    #   - DB_CONNECTION: circle_testing
    # working_directory: ~/p
    # steps:
    #   - checkout
    #   - run:
    #       name: Update apt-get
    #       command: sudo apt-get update
    #   - run:
    #       name: Docker php extensions install
    #       command: sudo docker-php-ext-install pdo_mysql
    #   - restore_cache:
    #       keys:
    #         - v1-dependencies-{{ checksum "composer.json" }}
    #         - v1-dependencies-
    #   - run:
    #       name: Install PHP libraries
    #       command: cd app && composer install -n --prefer-dist
    #   - save_cache:
    #       paths:
    #         - ./vendor
    #       key: v1-dependencies-{{ checksum "composer.json" }}
    #   - run:
    #       name: Run PHPUnit
    #       command: cd app && vendor/bin/phpunit

#   deploy:
#     machine:
#       image: circleci/classic:201808-01
#     steps:
#       - checkout
#       - add_ssh_keys:
#           fingerprints:
#             - "${KEY_FINGERPRINT}"  
#       - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/app/ && git pull origin master '

 
# workflows:
#   version: 2
#   build_and_deploy:
#     jobs:
#       - build
#       - dusk
#       - deploy:
#           requires:
#             - build
#             - dusk
#           filters:
#             branches:
#               only: master