version: 2
jobs:
  build:
    override:
      - vendor/bin/phpunit
      - ./vendor/laravel/dusk/bin/chromedriver-linux:
            background: true
      - php artisan serve:
            background: true
      - php artisan dusk

  deploy:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${KEY_FINGERPRINT}"  
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/app/ && git pull origin master '

 
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master